CREATE TABLE [dbo].[CharacterInfo] (
    [Character_id]   INT           IDENTITY (1, 1) NOT NULL,
    [Name]           NVARCHAR (50) NOT NULL,
    [Origin]         NVARCHAR (50) NOT NULL,
    [Companion]      NVARCHAR (50) NOT NULL,
    [Role]           NVARCHAR (50) NOT NULL,
    [SpecialAbility] NVARCHAR (50) NOT NULL,
    [FaceShape]      NVARCHAR (50) NOT NULL,
    [HairLength]     NVARCHAR (50) NOT NULL,
    [HairColor]      NVARCHAR (50) NOT NULL,
    [HairType]       NVARCHAR (50) NOT NULL,
    [BodyType]       NVARCHAR (50) NOT NULL,
    [EyeColor]       NVARCHAR (50) NOT NULL,
    [MouthType]      NVARCHAR (50) NOT NULL,
    [Height]         NVARCHAR (50) NOT NULL,
    [Race]           NVARCHAR (50) NOT NULL,
    [Gender]         NVARCHAR (50) NOT NULL,
    [Personality]    NVARCHAR (50) NOT NULL,
    [Skin]           NVARCHAR (50) NOT NULL,
    [ShirtType]      NVARCHAR (50) NOT NULL,
    [BottomType]     NVARCHAR (50) NOT NULL,
    [Shoes]          NVARCHAR (50) NOT NULL,
    [Accessories]    NVARCHAR (50) NOT NULL,
    [Scar]           NVARCHAR (50) NOT NULL,
    [Strength]       INT           NOT NULL,
    [Defense]        INT           NOT NULL,
    [Luck]           INT           NOT NULL,
    [Stealth]        INT           NOT NULL,
    [Endurance]      INT           NOT NULL,
    [Stamina]        INT           NOT NULL,
    [Intelligence]   INT           NOT NULL,
    [Agility]        INT           NOT NULL,
    [Curse]          BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([Character_id] ASC)
);

